exclude: 'node_modules/bootstrap-sass/assets/stylesheets/_bootstrap-mincer.scss'

linters:
  PseudoElement:
    enabled: false

  SelectorFormat:
    enabled: false

  SelectorDepth:
    enabled: false